services:
  _defaults:
    public: false
    autowire: true

  OxidEsales\EshopCommunity\Internal\Review\Dao\ProductRatingDaoInterface:
    class: OxidEsales\EshopCommunity\Internal\Review\Dao\ProductRatingDao
    arguments:
      $mapper: '@oxid_esales.review.product_rating_mapper'
  OxidEsales\EshopCommunity\Internal\Review\Dao\RatingDaoInterface:
    class: OxidEsales\EshopCommunity\Internal\Review\Dao\RatingDao
    arguments:
      $mapper: '@oxid_esales.review.rating_mapper'
  OxidEsales\EshopCommunity\Internal\Review\Dao\ReviewDaoInterface:
    class: OxidEsales\EshopCommunity\Internal\Review\Dao\ReviewDao
    arguments:
      $mapper: '@oxid_esales.review.review_mapper'
