services:
  _defaults:
    autowire: true
    public: false

  OxidEsales\EshopCommunity\Internal\Module\Setting\SettingDaoInterface:
    class: OxidEsales\EshopCommunity\Internal\Module\Setting\SettingDao
