services:
  _defaults:
    autowire: true
    public: true
  OxidEsales\EshopCommunity\Internal\Review\Bridge\UserReviewBridgeInterface:
    class: %review_path%\Bridge\UserReviewBridge
  OxidEsales\EshopCommunity\Internal\Review\Bridge\UserRatingBridgeInterface:
    class: %review_path%\Bridge\UserRatingBridge
  OxidEsales\EshopCommunity\Internal\Review\Bridge\ProductRatingBridgeInterface:
    class: %review_path%\Bridge\ProductRatingBridge
  OxidEsales\EshopCommunity\Internal\Review\Bridge\UserReviewAndRatingBridgeInterface:
    class: %review_path%\Bridge\UserReviewAndRatingBridge
