services:
  _defaults:
    autowire: true
    public: false

  OxidEsales\EshopCommunity\Internal\Password\Bridge\PasswordServiceBridgeInterface:
    class: OxidEsales\EshopCommunity\Internal\Password\Bridge\PasswordServiceBridge
    public: true

  OxidEsales\EshopCommunity\Internal\Password\Service\PasswordHashServiceFactoryInterface:
    class: OxidEsales\EshopCommunity\Internal\Password\Service\PasswordHashServiceFactory
    calls:
        - [addPasswordHashStrategy, [PASSWORD_BCRYPT, "@OxidEsales\\EshopCommunity\\Internal\\Password\\Strategy\\PasswordHashBcryptStrategy"]]
        - [addPasswordHashStrategy, [PASSWORD_ARGON2I, "@OxidEsales\\EshopCommunity\\Internal\\Password\\Strategy\\PasswordHashArgon2IStrategy"]]
        - [addPasswordHashStrategy, [PASSWORD_ARGON2ID, "@OxidEsales\\EshopCommunity\\Internal\\Password\\Strategy\\PasswordHashArgon2IdStrategy"]]

  OxidEsales\EshopCommunity\Internal\Password\Strategy\PasswordHashBcryptStrategyOptionsProvider: ~

  OxidEsales\EshopCommunity\Internal\Password\Service\PasswordVerificationServiceInterface:
    class: OxidEsales\EshopCommunity\Internal\Password\Service\PasswordVerificationService

  OxidEsales\EshopCommunity\Internal\Password\Service\PasswordPolicyServiceInterface:
    class: OxidEsales\EshopCommunity\Internal\Password\Service\PasswordPolicyService

  OxidEsales\EshopCommunity\Internal\Password\Strategy\PasswordHashBcryptStrategy: ~

  OxidEsales\EshopCommunity\Internal\Password\Strategy\PasswordHashArgon2IdStrategy: ~

  OxidEsales\EshopCommunity\Internal\Password\Strategy\PasswordHashArgon2IStrategy: ~