services:
  _defaults:
    autowire: true
    public: false
  OxidEsales\EshopCommunity\Internal\Review\Service\UserRatingServiceInterface:
    class: %review_path%\Service\UserRatingService
  OxidEsales\EshopCommunity\Internal\Review\Service\UserReviewServiceInterface:
    class: %review_path%\Service\UserReviewService
  OxidEsales\EshopCommunity\Internal\Review\Service\ReviewAndRatingMergingServiceInterface:
    class: %review_path%\Service\ReviewAndRatingMergingService
  OxidEsales\EshopCommunity\Internal\Review\Service\UserReviewAndRatingServiceInterface:
    class: %review_path%\Service\UserReviewAndRatingService
  OxidEsales\EshopCommunity\Internal\Review\Service\RatingCalculatorServiceInterface:
    class: %review_path%\Service\RatingCalculatorService
  OxidEsales\EshopCommunity\Internal\Review\Service\ProductRatingServiceInterface:
    class: %review_path%\Service\ProductRatingService
