parameters:
  utility_path: OxidEsales\EshopCommunity\Internal\Utility

services:
  _defaults:
    autowire: true
    public: false
  OxidEsales\Eshop\Core\Config:
    class: OxidEsales\Eshop\Core\Config
    factory: ['OxidEsales\Eshop\Core\Registry', getConfig]
  OxidEsales\EshopCommunity\Internal\Utility\ContextInterface:
    class: %utility_path%\Context
