services:
  _defaults:
    autowire: true
    public: false

  OxidEsales\EshopCommunity\Internal\Module\TemplateExtension\TemplateBlockExtensionDaoInterface:
    class: OxidEsales\EshopCommunity\Internal\Module\TemplateExtension\TemplateBlockExtensionDao
