services:
  _defaults:
    autowire: true
    public: false

  oxid_esales.module.install.service.launched_shop_project_configuration_generator:
    class: OxidEsales\EshopCommunity\Internal\Module\Install\Service\ProjectConfigurationGenerator
    arguments:
      $context: '@OxidEsales\EshopCommunity\Internal\Utility\ContextInterface'
    public: true