services:
  _defaults:
    autowire: true
    public: false
  Doctrine\DBAL\Connection:
    factory: ['OxidEsales\EshopCommunity\Internal\Common\Factory\ConnectionFactory', get]
    class: Doctrine\DBAL\Connection
  OxidEsales\EshopCommunity\Internal\Common\Database\QueryBuilderFactoryInterface:
    class: OxidEsales\EshopCommunity\Internal\Common\Database\QueryBuilderFactory
  OxidEsales\EshopCommunity\Internal\Common\Form\FormBuilderInterface:
    class: OxidEsales\EshopCommunity\Internal\Common\Form\FormBuilder
  common.form.required_fields_validator:
    class: OxidEsales\EshopCommunity\Internal\Common\Form\RequiredFieldsValidator
