services:
  _defaults:
    autowire: true
    public: false

  OxidEsales\EshopCommunity\Internal\Container\Utility\BasicContextInterface:
    class: OxidEsales\EshopCommunity\Internal\Container\Utility\BasicContext
    public: true
