services:
  _defaults:
    autowire: true
    public: true
  event_dispatcher:
    class: OxidEsales\EshopCommunity\Internal\Application\Events\ShopAwareEventDispatcher
    arguments:
      $container: '@service_container'

