services:
  _defaults:
    autowire: true
    public: false
  oxid_esales.review.product_rating_mapper:
    class: %review_path%\DataMapper\ProductRatingDataMapper
  oxid_esales.review.rating_mapper:
    class: %review_path%\DataMapper\RatingDataMapper
  oxid_esales.review.review_mapper:
    class: %review_path%\DataMapper\ReviewDataMapper
