services:
  _defaults:
    autowire: true
    public: false

  OxidEsales\Eshop\Core\Config:
    class: OxidEsales\Eshop\Core\Config
    factory: ['OxidEsales\Eshop\Core\Registry', getConfig]
  OxidEsales\Eshop\Core\UtilsView:
    class: OxidEsales\Eshop\Core\UtilsView
    factory: ['OxidEsales\Eshop\Core\Registry', getUtilsView]
  OxidEsales\EshopCommunity\Internal\Smarty\SmartyContextInterface:
    class: OxidEsales\EshopCommunity\Internal\Smarty\SmartyContext
  OxidEsales\EshopCommunity\Internal\Smarty\Configuration\SmartyConfigurationFactoryInterface:
    class: OxidEsales\EshopCommunity\Internal\Smarty\Configuration\SmartyConfigurationFactory
  OxidEsales\EshopCommunity\Internal\Smarty\Configuration\SmartySettingsDataProviderInterface:
    class: OxidEsales\EshopCommunity\Internal\Smarty\Configuration\SmartySettingsDataProvider
  OxidEsales\EshopCommunity\Internal\Smarty\Configuration\SmartySecuritySettingsDataProviderInterface:
    class: OxidEsales\EshopCommunity\Internal\Smarty\Configuration\SmartySecuritySettingsDataProvider
  OxidEsales\EshopCommunity\Internal\Smarty\Configuration\SmartyResourcesDataProviderInterface:
    class: OxidEsales\EshopCommunity\Internal\Smarty\Configuration\SmartyResourcesDataProvider
  OxidEsales\EshopCommunity\Internal\Smarty\Configuration\SmartyPrefiltersDataProviderInterface:
    class: OxidEsales\EshopCommunity\Internal\Smarty\Configuration\SmartyPrefiltersDataProvider
  OxidEsales\EshopCommunity\Internal\Smarty\Configuration\SmartyPluginsDataProviderInterface:
    class: OxidEsales\EshopCommunity\Internal\Smarty\Configuration\SmartyPluginsDataProvider
  OxidEsales\EshopCommunity\Internal\Smarty\Configuration\SmartyConfigurationInterface:
    class: OxidEsales\EshopCommunity\Internal\Smarty\Configuration\SmartyConfiguration
    factory: 'OxidEsales\EshopCommunity\Internal\Smarty\Configuration\SmartyConfigurationFactoryInterface:getConfiguration'
  OxidEsales\EshopCommunity\Internal\Smarty\Bridge\SmartyEngineBridgeInterface:
    class: OxidEsales\EshopCommunity\Internal\Smarty\Bridge\SmartyEngineBridge
  smarty.smarty_engine_factory:
    class: OxidEsales\EshopCommunity\Internal\Smarty\Legacy\LegacySmartyEngineFactory
  OxidEsales\EshopCommunity\Internal\Framework\Templating\TemplateEngineInterface:
    class: OxidEsales\EshopCommunity\Internal\Smarty\Legacy\LegacySmartyEngine
    factory: 'smarty.smarty_engine_factory:getTemplateEngine'
  OxidEsales\EshopCommunity\Internal\Framework\Templating\TemplateRendererBridgeInterface:
    class: OxidEsales\EshopCommunity\Internal\Smarty\Bridge\SmartyTemplateRendererBridge
    public: true
