imports:
    - { resource: Framework/DIContainer/services.yaml }
    - { resource: Framework/services.yaml }
    - { resource: Domain/services.yaml }
    - { resource: Transition/Adapter/services.yaml }
    - { resource: Framework/Smarty/services.yaml }
    - { resource: Transition/Utility/services.yaml }
