imports:
    - { resource: Application/services.yaml }
    - { resource: Utility/services.yaml }
    - { resource: Framework/services.yaml }
    - { resource: Domain/services.yaml }
    - { resource: Adapter/services.yaml }
    - { resource: Smarty/services.yaml }
