services:
  _defaults:
    autowire: true
    public: false

  OxidEsales\EshopCommunity\Internal\Application\Utility\BasicContextInterface:
    class: OxidEsales\EshopCommunity\Internal\Application\Utility\BasicContext
    public: true
